version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: src/docs/requirements_docs.txt
    - method: pip
      path: .

sphinx:
  configuration: src/docs/conf.py
  fail_on_warning: false
