# c-PMAT/ c-pmat

## Install

First set up a new conda environment with some basic dependencies:

``` sh

conda create -n c-pmat python==3.9 pip ipykernel
```

Then activate the environment and install the package:

``` sh
conda activate c-pmat
```

``` sh
pip install c-pmat
```
